// libs/ui/src/form/CheckboxButton/CheckboxButton.tsx
'use client';

import { CheckboxValue } from './CheckboxButton.types';
import './CheckboxButton.styles.scss';

interface Props {
  name: string;
  value: CheckboxValue;
  modelValue?: CheckboxValue[];
  isDisabled?: boolean;
  label?: string;
  ariaLabel?: string;
  onChange: (value: CheckboxValue[]) => void;
}

export const CheckboxButton = ({
  name,
  value,
  modelValue = [],
  isDisabled = false,
  label,
  ariaLabel,
  onChange,
}: Props) => {
  const isChecked = modelValue.includes(value);

  const handleToggle = () => {
    if (isDisabled) return;

    const newValue = isChecked
      ? modelValue.filter((v) => v !== value)
      : [...modelValue, value];

    onChange(newValue);
  };

  return (
    <label className={`checkbox ${isDisabled ? 'checkbox--disabled' : ''}`}>
      <input
        name={name}
        className="checkbox__input"
        type="checkbox"
        checked={isChecked}
        disabled={isDisabled}
        onChange={handleToggle}
        aria-label={!label ? ariaLabel : undefined}
      />

      <span className="checkbox__ui" aria-hidden="true" />

      {label && <span className="checkbox__label">{label}</span>}
    </label>
  );
};

// src/shared/form/CheckboxButton/CheckboxButton.vue
<script setup lang="ts">
  import { computed } from "vue";

  interface Props {
    value: string | number;
    modelValue?: Array<string | number>;
    isDisabled?: boolean;
    label: string;
  }

  const props = defineProps<Props>();

  const emit = defineEmits<{
    (e: "update:modelValue", value: Array<string | number>): void;
  }>();

  const isChecked = computed(() => {
    const current = props.modelValue ?? [];
    return current.includes(props.value);
  });

  const handleToggle = () => {
    if (props.isDisabled) return;

    const current = props.modelValue ?? [];
    const newValue = current.includes(props.value)
      ? current.filter((v) => v !== props.value)
      : [...current, props.value];

    emit("update:modelValue", newValue);
  };
</script>

<template>
  <label class="checkbox" :class="{ 'checkbox--disabled': isDisabled }">
    <input
      class="checkbox__input"
      type="checkbox"
      :checked="isChecked"
      :disabled="isDisabled"
      @change="handleToggle"
    />

    <span v-if="label" class="checkbox__label">{{ label }}</span>
  </label>
</template>

<style scoped>
  .checkbox {
    display: inline-flex;
    align-items: center;
    gap: 8px;
    cursor: pointer;
    user-select: none;
  }

  .checkbox--disabled {
    cursor: not-allowed;
    opacity: 0.6;
  }

  .checkbox__input {
    cursor: inherit;
  }

  .checkbox__label {
    cursor: inherit;
  }
</style>
