// src/shared/form/CheckboxGroup/CheckboxGroup.vue
<script setup lang="ts">
  import { computed, onMounted, ref, watch } from "vue";
  import CheckboxButton from "@/shared/form/CheckboxButton/CheckboxButton.vue";
  import type { CheckboxOption } from "./types";

  interface Props {
    options: CheckboxOption[];
    defaultSelected?: Array<string | number>;
    label?: string;
    modelValue?: Array<string | number>;
  }

  const props = defineProps<Props>();

  const emit = defineEmits<{
    (e: "update:modelValue", value: Array<string | number>): void;
  }>();

  const localSelected = ref<Array<string | number>>(
    props.defaultSelected ? [...props.defaultSelected] : []
  );

  const selected = computed<Array<string | number>>(() => {
    return props.modelValue ?? localSelected.value;
  });

  const handleChange = (newSelected: Array<string | number>) => {
    if (props.modelValue === undefined) {
      localSelected.value = newSelected;
    }
    emit("update:modelValue", newSelected);
  };

  onMounted(() => {
    if (props.modelValue === undefined && props.defaultSelected?.length) {
      const initial = [...props.defaultSelected];
      localSelected.value = initial;
      emit("update:modelValue", initial);
    }
  });

  watch(
    () => props.modelValue,
    (val) => {
      if (val !== undefined) return;
      localSelected.value = props.defaultSelected ? [...props.defaultSelected] : [];
    }
  );
</script>

<template>
  <div class="checkbox-group">
    <div v-if="label" class="checkbox-group__label">
      {{ label }}
    </div>

    <div class="checkbox-group__list">
      <CheckboxButton
        v-for="option in options"
        :key="String(option.value)"
        :value="option.value"
        :label="option.label ?? String(option.value)"
        :is-disabled="option.disabled"
        :model-value="selected"
        @update:model-value="handleChange"
      />
    </div>
  </div>
</template>

<style scoped lang="scss">
  .checkbox-group {
    display: grid;
    gap: 8px;

    &__label {
      font-weight: 600;
    }

    &__list {
      display: flex;
      flex-wrap: wrap;
      gap: 12px;
    }
  }
</style>

// libs/ui/src/form/CheckboxGroup/CheckboxGroup.tsx
'use client';

import { useState } from 'react';
import { CheckboxButton } from '../CheckboxButton/CheckboxButton';
import { CheckboxOption } from './CheckboxGroup.types';
import { CheckboxValue } from '../CheckboxButton';
import './CheckboxGroup.styles.scss';

interface Props {
  name: string;
  options: CheckboxOption[];
  defaultSelected?: CheckboxValue[];
  label?: string;
  modelValue?: CheckboxValue[];
  onChange?: (value: CheckboxValue[]) => void;
}

export const CheckboxGroup = ({
  name,
  options,
  defaultSelected = [],
  label,
  modelValue,
  onChange,
}: Props) => {
  const [internalSelected, setInternalSelected] =
    useState<CheckboxValue[]>(defaultSelected);

  const isControlled = modelValue !== undefined;
  const currentSelected = isControlled ? modelValue : internalSelected;

  const handleChange = (newValue: CheckboxValue[]) => {
    if (!isControlled) {
      setInternalSelected(newValue);
    }

    onChange?.(newValue);
  };

  return (
    <div className="checkbox-group">
      {label && <div className="checkbox-group__label">{label}</div>}

      <div className="checkbox-group__list">
        {options.map((option) => (
          <CheckboxButton
            key={String(option.value)}
            name={name}
            value={option.value}
            label={option.label ?? String(option.value)}
            isDisabled={option.disabled}
            modelValue={currentSelected}
            onChange={handleChange}
          />
        ))}
      </div>
    </div>
  );
};
